#include "Model/include/ModelGenerator.h"
#include "Core/Buffer/include/Buffer.h"
#include "Core/FilesSystem/include/FilesSystem.h"
#include <sstream>
#include <iomanip>

namespace X_Y::Model {

bool GenerateBoxOBJ(float width, float height, float depth,
                    const std::string& outputPath, std::string& err)
{
    if (width <= 0.0f || height <= 0.0f || depth <= 0.0f)
    {
        err = "Dimensions must be positive";
        return false;
    }

    float hw = width  * 0.5f;
    float hh = height * 0.5f;
    float hd = depth  * 0.5f;

    std::ostringstream oss;
    oss << std::fixed << std::setprecision(6);

    // ── 8 个顶点位置 ──
    // 编号:  0=---, 1=+--, 2=++-, 3=-+-, 4=--+, 5=+-+, 6=+++, 7=-++
    oss << "# Box " << width << " x " << height << " x " << depth << "\n";
    oss << "# Generated by ModelGenerator\n\n";

    // vertices
    oss << "v " << -hw << " " << -hh << " " << -hd << "\n"; // 0
    oss << "v " <<  hw << " " << -hh << " " << -hd << "\n"; // 1
    oss << "v " <<  hw << " " <<  hh << " " << -hd << "\n"; // 2
    oss << "v " << -hw << " " <<  hh << " " << -hd << "\n"; // 3
    oss << "v " << -hw << " " << -hh << " " <<  hd << "\n"; // 4
    oss << "v " <<  hw << " " << -hh << " " <<  hd << "\n"; // 5
    oss << "v " <<  hw << " " <<  hh << " " <<  hd << "\n"; // 6
    oss << "v " << -hw << " " <<  hh << " " <<  hd << "\n"; // 7

    // ── 6 个面的法线 ──
    oss << "\n";
    oss << "vn " <<  0 << " " <<  0 << " " <<  1 << "\n"; // +Z
    oss << "vn " <<  0 << " " <<  0 << " " << -1 << "\n"; // -Z
    oss << "vn " <<  1 << " " <<  0 << " " <<  0 << "\n"; // +X
    oss << "vn " << -1 << " " <<  0 << " " <<  0 << "\n"; // -X
    oss << "vn " <<  0 << " " <<  1 << " " <<  0 << "\n"; // +Y
    oss << "vn " <<  0 << " " << -1 << " " <<  0 << "\n"; // -Y

    // ── 12 个三角面（6 个面各 2 个三角，每个三角 3 个顶点索引 v//vn） ──
    // OBJ 索引是 1-based
    oss << "\n";

    // 前面 (+Z): 顶点 4,5,6,7 法线 1
    oss << "f 4//1 5//1 6//1\n";
    oss << "f 4//1 6//1 7//1\n";

    // 后面 (-Z): 顶点 1,0,3,2 法线 2
    oss << "f 1//2 0//2 3//2\n";
    oss << "f 1//2 3//2 2//2\n";

    // 右面 (+X): 顶点 5,1,2,6 法线 3
    oss << "f 5//3 1//3 2//3\n";
    oss << "f 5//3 2//3 6//3\n";

    // 左面 (-X): 顶点 0,4,7,3 法线 4
    oss << "f 0//4 4//4 7//4\n";
    oss << "f 0//4 7//4 3//4\n";

    // 上面 (+Y): 顶点 7,6,2,3 法线 5
    oss << "f 7//5 6//5 2//5\n";
    oss << "f 7//5 2//5 3//5\n";

    // 下面 (-Y): 顶点 0,1,5,4 法线 6
    oss << "f 0//6 1//6 5//6\n";
    oss << "f 0//6 5//6 4//6\n";

    oss << "\n";

    // ── 写入文件 ──
    std::string text = oss.str();
    Buffer buf(text.size());
    buf.Append(text.data(), text.size());

    if (!X_Y::FilesSystem::WriteFileBinary(outputPath, buf))
    {
        err = "Failed to write file: " + outputPath;
        return false;
    }

    return true;
}

} // namespace X_Y::Model
