#include "Model/include/ModelGenerator.h"
#include "Core/Buffer/include/Buffer.h"
#include "Core/FilesSystem/include/FilesSystem.h"
#include <sstream>
#include <iomanip>

namespace X_Y::Model {

bool GenerateBoxOBJ(float width, float height, float depth,
                    const std::string& outputPath, std::string& err)
{
    if (width <= 0.0f || height <= 0.0f || depth <= 0.0f)
    {
        err = "Dimensions must be positive";
        return false;
    }

    float hw = width  * 0.5f;
    float hh = height * 0.5f;
    float hd = depth  * 0.5f;

    std::ostringstream oss;
    oss << std::fixed << std::setprecision(6);

    // ── 8 个顶点位置 ──
    // 编号:  0=---, 1=+--, 2=++-, 3=-+-, 4=--+, 5=+-+, 6=+++, 7=-++
    oss << "# Box " << width << " x " << height << " x " << depth << "\n";
    oss << "# Generated by ModelGenerator\n\n";

    // vertices
    oss << "v " << -hw << " " << -hh << " " << -hd << "\n"; // 0
    oss << "v " <<  hw << " " << -hh << " " << -hd << "\n"; // 1
    oss << "v " <<  hw << " " <<  hh << " " << -hd << "\n"; // 2
    oss << "v " << -hw << " " <<  hh << " " << -hd << "\n"; // 3
    oss << "v " << -hw << " " << -hh << " " <<  hd << "\n"; // 4
    oss << "v " <<  hw << " " << -hh << " " <<  hd << "\n"; // 5
    oss << "v " <<  hw << " " <<  hh << " " <<  hd << "\n"; // 6
    oss << "v " << -hw << " " <<  hh << " " <<  hd << "\n"; // 7

    // ── 6 个面的法线 ──
    oss << "\n";
    oss << "vn " <<  0 << " " <<  0 << " " <<  1 << "\n"; // +Z
    oss << "vn " <<  0 << " " <<  0 << " " << -1 << "\n"; // -Z
    oss << "vn " <<  1 << " " <<  0 << " " <<  0 << "\n"; // +X
    oss << "vn " << -1 << " " <<  0 << " " <<  0 << "\n"; // -X
    oss << "vn " <<  0 << " " <<  1 << " " <<  0 << "\n"; // +Y
    oss << "vn " <<  0 << " " << -1 << " " <<  0 << "\n"; // -Y

    // ── 12 个三角面（6 个面各 2 个三角，每个三角 3 个顶点索引 v//vn） ──
    // OBJ 索引是 1-based
    oss << "\n";

    // front (+Z): vertices 4,5,6,7 normal 1
    oss << "f 5//1 6//1 7//1\n";
    oss << "f 5//1 7//1 8//1\n";

    // back (-Z): vertices 1,0,3,2 normal 2
    oss << "f 2//2 1//2 4//2\n";
    oss << "f 2//2 4//2 3//2\n";

    // right (+X): vertices 5,1,2,6 normal 3
    oss << "f 6//3 2//3 3//3\n";
    oss << "f 6//3 3//3 7//3\n";

    // left (-X): vertices 0,4,7,3 normal 4
    oss << "f 1//4 5//4 8//4\n";
    oss << "f 1//4 8//4 4//4\n";

    // top (+Y): vertices 7,6,2,3 normal 5
    oss << "f 8//5 7//5 3//5\n";
    oss << "f 8//5 3//5 4//5\n";

    // bottom (-Y): vertices 0,1,5,4 normal 6
    oss << "f 1//6 2//6 6//6\n";
    oss << "f 1//6 6//6 5//6\n";

    oss << "\n";

    // ── 写入文件 ──
    std::string text = oss.str();
    Buffer buf(text.size());
    buf.Append(text.data(), text.size());

    if (!X_Y::FilesSystem::WriteFileBinary(outputPath, buf))
    {
        err = "Failed to write file: " + outputPath;
        return false;
    }

    return true;
}



} // namespace X_Y::Model
